project:
  type: sdca-theme

website:
  title: "**2EARLY**"
  site-url: "https://steno-aarhus.github.io/2early/"
  repo-url: "https://steno-aarhus.github.io/2early/"
  page-navigation: true
  search: true

  # TODO: Remove announcement when website is ready
  announcement: 
    icon: info-circle
    content: "This website is a work in progress and might contain incomplete or placeholder content."
    type: light

  navbar:
    right: 
    - text: "WP1"
      href: 1-wp1.qmd
    - text: "WP2"
      href: 2-wp2.qmd
    - text: "WP3"
      href: 3-wp3.qmd
    - text: "WP4"
      href: 4-wp4.qmd 
    - text: "WP5"
      href: 5-wp5.qmd 
    - text: "Kontakt"
      href: 5-kontakt.qmd
    - text: "For patienter"
      href: 5-forpatienter.qmd
      
    tools:
      - icon: github
        href: https://steno-aarhus.github.io/2early/
        text: "2early"
        aria-label: "GitHub icon: Source repository"

format:
  sdca-theme-html:
    theme:
      - brand
      - custom-styles.scss



