project:
  type: sdca-theme

website:
  title: "2Early"
  site-url: "https://steno-aarhus.github.io/2early/"
  repo-url: "https://github.com/steno-aarhus/2early"
  navbar:
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/2early"

format:
  sdca-theme-html:
    theme:
      - brand
      - custom-styles.scss

editor: 
  markdown:
    wrap: 72
    canonical: true
