project:
  type: sdca-theme

website:
  title: "EOT2D"
  site-url: "https://steno-aarhus.github.io/eot2d/"
  repo-url: "https://github.com/steno-aarhus/eot2d"
  navbar:
    tools:
      - icon: github
        href: "https://github.com/steno-aarhus/eot2d"

format:
  sdca-theme-html:
    theme:
      - brand
      - custom-styles.scss

editor: 
  markdown:
    wrap: 72
    canonical: true
